### PR TITLE
Added Fedora support

### PR DESCRIPTION
**Pull request by Kaurin**
Hi guys,

line 23 had some extra spaces, my editor fixed that.

Other than that, I added Fedora support. Not sure how you feel about inclusion of the "vars" directory, but that can be done differently depending on what you'd prefer. I don't mind doing the work

Do let me know.

Thanks! :)

### CODE REVIEW

**Review by SlothOfAnarchy — DISMISSED** [review]
Hi,
no, it's fine, it's a clever way to configure this. Thanks for contributing!

**Comment by SlothOfAnarchy** [comment]
On second thought, I think we can refactor the `install` tasks while we`re at it, something like
```yml
- name: Install smartmontools
  package:
    name: smartmontools
  when: ansible_pkg_mgr in ["apt", "pacman", "dnf"]
```
This should work because the package name is the same across these distributions, I didn't test it though.
Let me know if you want to try this, otherwise I'll do it.

**Comment by Kaurin** [comment]
I'll try it :)

**Comment by Kaurin** [comment]
Tested with my playbook that deploys to Debian/Fedora/Ubuntu, and there were no issues.

Small note: dnf module does not have the update_cache functionality, so that's not included.

**Review by SlothOfAnarchy — APPROVED** [review]
Looks good, thank you!

**Pull request merged**
